name: Debug with tmate
on: [push]
jobs:
  setup-tmate:
    runs-on: ubuntu-latest
    outputs:
      ssh-command: $
      ssh-address: $
    steps:
    - uses: actions/checkout@v4
    - name: Setup tmate session
      id: tmate
      uses: mxschmitt/action-tmate@v3
      with:
        detached: true
        
  use-ssh-command:
    needs: setup-tmate
    runs-on: ubuntu-latest
    steps:
    - name: Display SSH command
      run: |
        # Send a Slack message to someone telling them they can ssh to $
