name: Debug with tmate
   on:
     push:
       branches:
         - main
     workflow_dispatch:
       inputs:
         debug_enabled:
           description: 'Run the build with tmate debugging enabled'
           type: boolean
           required: false
           default: false

   jobs:
     debug:
       runs-on: ubuntu-latest
       steps:
         - name: Checkout code
           uses: actions/checkout@v4

         - name: Setup tmate session
           if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled || github.event_name == 'push' }}
           uses: mxschmitt/action-tmate@v3
           with:
             limit-access-to-actor: true
             connect-timeout-seconds: 600
             detached: true
             tmate-server-web-port: 80
